services:
 postgres:
  container_name: postgres_db
  image: postgres
  environment:
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_USER=postgres
   - POSTGRES_DB=test
  volumes:
   - ./pgdata:/var/lib/postgresql/data
  ports:
   - "6432:5432"
  healthcheck:
   test: [ "CMD-SHELL", "pg_isready -U postgres -d test" ]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 10s
  restart: unless-stopped